Info support
GillGate/delivery-bot pull request #14
Opened 2024-06-24 14:55 UTC by PaskeyDuet

- Admin panel (almost complete ver)
- db complete fix (I hope)
- visual changes (images added)
- rates api fixed (almost)
- now we also ask for phone number
- little fixes across the whole code

2024-06-25 18:57 UTC, GillGate requested changes

2024-06-25 18:57 UTC, GillGate commented on actions/cart.js
> -    let user = await getUserData(ctx);
почему?

2024-06-25 18:57 UTC, GillGate commented on conversations/calculate.js
> +    let chatId = ctx.update.callback_query.message.chat.id;
можно так: ctx.callbackQuery.message.chat.id;

2024-06-25 18:57 UTC, GillGate commented on conversations/helpers/getUserNumber.js
> +     const numberRegex = /^\+\d+$/;
Учитывая условие при ошибке правильнее будет регулярка: /^\+7\d{7,9}$/
А ещё лучше использовать что-то [такое](https://habr.com/ru/articles/110731), где могут быть номера на 8...

2024-06-25 18:57 UTC, GillGate commented on conversations/registration.js
> +            let numberText = "Укажите номер телефона получателя посылки в следующем формате:\n"
Учитывая коммент выше лучше просто попросить указать номер без конкретного формата, некорректный выдаст ошибку а форматировать всё что не цифры можно будет самому при записи в базу

2024-06-25 18:57 UTC, GillGate commented on conversations/registration.js
> +            await (currentOrder.fromId = from.id)
а зачем тут await если выше все данные уже есть?

2024-06-25 18:57 UTC, GillGate commented on conversations/registration.js
> +        textForManager += `Contact: @${from?.username /*?? altUsername*/}`;
да кто такой этот altUsername

2024-06-25 18:57 UTC, GillGate commented on conversations/updateOrderStatus.js
> +    await ctx.reply('JOB IS DONE')
Можно просто реакт какой-нибудь на сообщение повесить:
`ctx.react('👌');`

2024-06-25 18:57 UTC, GillGate commented on handlers/sendAdminMessage.js
> +        await ctx.reply('NO')
Никаких NO, просто игнор

2024-06-25 18:57 UTC, GillGate commented on helpers/statusParser.js
> +import { infoRegExps } from "#bot/config/regexp.config.js";
назови его как-нибудь обособлено, слишком общее название для такого файла
Тот же infoRegExps.config

2024-06-25 18:57 UTC, GillGate commented on helpers/statusParser.js
> +          await updateOrderStatus(userDbId, orderDbId, status);
для надёжности не помешает обернуть эти две функции в try catch

2024-06-25 18:57 UTC, GillGate commented on keyboards/registration.js
> +import { InlineKeyboard, Keyboard } from "grammy";
лишний import Keyboard

2024-06-26 10:12 UTC, PaskeyDuet commented on actions/cart.js
> -    let user = await getUserData(ctx);
Строка не использовалась :( Оставил её комментарием

2024-06-26 10:33 UTC, PaskeyDuet commented on conversations/updateOrderStatus.js
> +    await ctx.reply('JOB IS DONE')
JOB IS DONE better

2024-06-27 08:23 UTC, GillGate requested changes

2024-06-27 08:23 UTC, GillGate commented on config/infoRegExps.config.js
> +     numberRegex: /^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$/,
Этому тут не место

2024-06-27 08:23 UTC, GillGate commented on conversations/registration.js
>              let numberText = "Укажите номер телефона получателя посылки в следующем формате:\n"
Формата больше нет

2024-06-27 08:56 UTC, GillGate approved these changes

2024-06-27 08:57 UTC, merged